version: 2.1

orbs:
  node: circleci/node@5 

executors:
  sonar-executor:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/project

jobs:
  test-backend:
    executor: node/default
    working_directory: ~/project/BACKEND
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm

  build-frontend:
    executor: node/default
    working_directory: ~/project/src
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Create artifacts directory
          command: mkdir -p ~/artifacts
      - run:
          name: Copy frontend build artifacts
          command: |
            cp -R build ~/artifacts/build || true
            cp -R dist ~/artifacts/dist || true
      - store_artifacts:
          path: ~/artifacts
          destination: frontend-build

  sonarcloud:
    executor: sonar-executor
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Download and install OpenJDK 17.0.13+11
          command: |
            curl -sSL -o ~/project/openjdk-17.0.13+11.tar.gz https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.13+11/OpenJDK17U-jdk_x64_linux_hotspot_17.0.13_11.tar.gz

            if [ ! -f ~/project/openjdk-17.0.13+11.tar.gz ]; then
              echo "OpenJDK tarball not found, aborting!"
              exit 1
            fi

            tar -xzf ~/project/openjdk-17.0.13+11.tar.gz -C $HOME

            echo "export JAVA_HOME=\$HOME/jdk-17.0.13+11" >> $BASH_ENV
            echo "export PATH=\$JAVA_HOME/bin:\$PATH" >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Install SonarScanner 4.6.2
          command: |
            curl -sSLo sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
            unzip sonar-scanner-cli.zip -d $HOME
            echo "export PATH=\$HOME/sonar-scanner-4.6.2.2472-linux/bin:\$PATH" >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Run SonarCloud analysis
          command: |
            sonar-scanner \
              -Dsonar.projectKey=st10150631 \
              -Dsonar.organization=Mike_Turner \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=5d76a818b8dad8476e5412fc8843a6a335d1f078

workflows:
  build-and-test:
    jobs:
      - test-backend
      - build-frontend:
          requires:
            - test-backend
      - sonarcloud:
          requires:
            - build-frontend
