version: 2.1

orbs:
  node: circleci/node@5 

executors:
  sonar-executor:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/project

jobs:
  test-backend:
    executor: node/default
    working_directory: ~/project/BACKEND
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm

  build-frontend:
    executor: node/default
    working_directory: ~/project/src
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Create artifacts directory
          command: mkdir -p ~/artifacts
      - run:
          name: Copy frontend build artifacts
          command: |
            cp -R build ~/artifacts/build || true
            cp -R dist ~/artifacts/dist || true
      - store_artifacts:
          path: ~/artifacts
          destination: frontend-build

  sonarcloud:
    executor: sonar-executor
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install SonarScanner
          command: |
            curl -sSLo sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.4.0.2170-linux.zip
            unzip sonar-scanner-cli.zip -d $HOME
            echo "export PATH=\$HOME/sonar-scanner-4.4.0.2170-linux/bin:\$PATH" >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Run SonarCloud analysis
          command: |
            sonar-scanner \
              -Dsonar.projectKey=st10150631 \
              -Dsonar.organization=Mike_Turner \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=5d76a818b8dad8476e5412fc8843a6a335d1f078

workflows:
  build-and-test:
    jobs:
      - test-backend
      - build-frontend:
          requires:
            - test-backend
      - sonarcloud:
          requires:
            - build-frontend
